-name: variables from PLAY level
 hosts: localhost
 vars:
  course: "Devops"
  name: "Ajay"
 tasks:
 -name: check variables
  vars: #task level
    course: "Devops with aws"
  ansible.builtin.debug:
    msg: "hi , {{name}} welcome to {{course}} "